on: create

name: Release

jobs:
  release:
    name: Release GitHub Actions
    runs-on: ubuntu-latest
    steps:
#      - name: Checkout
#        uses: actions/checkout@master
#        with:
#          fetch-depth: 3
#      - name: Check package version
#        uses: technote-space/package-version-check-action@test/v1
#        with:
#          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Release GitHub Actions
        uses: technote-space/release-github-actions@test/v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_NAME: Technote
          COMMIT_EMAIL: technote.space@gmail.com
          OUTPUT_BUILD_INFO_FILENAME: build.json
          TEST_TAG_PREFIX: test/
          ORIGINAL_TAG_PREFIX: original/

#      - uses: 8398a7/action-slack@v1
#        with:
#          type: failure
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
#        if: failure()
